apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "starter-kit.fullname" . }}-envvars
  labels:
    app.kubernetes.io/name: {{ include "starter-kit.name" . }}-envvars
    helm.sh/chart: {{ include "starter-kit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
data:
  DB2_HOST: db2.db2.svc
  DB2_PORT: "50000"
  DB2_DBNAME: ORDERDB
  DB2_USER: db2inst1
  DB2_PASSWORD: db2inst1
